### PR TITLE
Adds Multiple Linear Regression to the time models

### PR DESCRIPTION
**Pull request by kdschlosser**
As the title states. Adds Multiple Linear Regression to the time models.

### CODE REVIEW

**Comment by Joshua-Data-Wizard** [comment]
Good Morning Kevin! I hope that your day is going well and Thank you so much for helping to improve the code it is greatly appreciated. I was able to merge the first two pull requests but this last one is having a merge conflict. I think it might be from adding the type hinting and the multiple regression in the Time_trending.py.  I didn't want to change some thing other then what you are intending and was wondering if you would mind taking a look thank you!

**Comment by kdschlosser** [comment]
This one may cause issues because of the other 2 PR's being added first. Lemme refactor the code in the PR so the changes made in those PR's are populated to this one. Give me a few minutes to get that sorted out.

**Comment by kdschlosser** [comment]
The merge issues have been corrected. All you need to do is a review and that will allow you to merge it.

**Comment by Joshua-Data-Wizard** [comment]
Awesome Thank you again Kevin, I really appreciate all your time and effort on this!

**Review by Joshua-Data-Wizard — APPROVED** [review]

**Comment by kdschlosser** [comment]
The other 2 PR's just make it easier to read the code and this one adds a missing way of calculating the time adjustments. 

I am happy to help. I am a self taught programmer and I fully understand the difficulties in learning a programming language without anyone helping. In order to get people interested in helping with a project the code needs to be easily understandable....

**Pull request merged**
