### PR TITLE
Adds requirements file 

### PR DESCRIPTION
**Pull request by kdschlosser**
Adds requirements,.txt file that holds a list of  dependencies
Completes the project information in pyproject.toml

### CODE REVIEW

**Review by Joshua-Data-Wizard — APPROVED** [review]
Thank you so much for taking your time to help improve the code it is greatly appreciated!

**Comment by kdschlosser** [comment]
no worries m8

**Comment by kdschlosser** [comment]
I can tell that Python is not your native programming language. It's not C either. I can usually tell what a persons native language is. the 2 space indents and the use of the parenthesis makes me think C but there were no semicolons at all. so I am on the fence about what language is your preferred.

**Comment by Joshua-Data-Wizard** [comment]
So to be completely honest I do not know that I have a preferred I jumped around allot in school but having a bachelors in math I have used R by far for the longest. I think what you are kind of seeing is me mixing and matching the languages.   I really do appreciate the review and straightening out of the code it is much cleaner!

**Comment by kdschlosser** [comment]
Not a big deal. There is nothing like this made for Python and it does help out a lot. Unfortunately there is no set standard across the country for doing home valuations and the only thing that can be made is something that makes a best efford to cover the different approaches.

Type hinting and documentation using the doc strings are a must to have so the user is able to tell what needs to be passed and what data needs to be passed.

**Pull request merged**
